# Generated by Django 4.2.16 on 2024-10-28 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('second_name', models.TextField()),
                ('third_name', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('level', models.IntegerField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('head_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.department')),
            ],
        ),
        migrations.CreateModel(
            name='KPI_Metric',
            fields=[
                ('kpi_metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_name', models.TextField()),
                ('description', models.TextField()),
                ('measurement_method', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('review', models.DateTimeField(blank=True, null=True)),
                ('assign_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('reviewing', 'Reviewing'), ('assigned', 'Assigned'), ('in_work', 'In Work'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('assigner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskKPI',
            fields=[
                ('task_kpi_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('kpi_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.kpi_metric')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEmployee',
            fields=[
                ('task_employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('employee_kpi_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_value', models.IntegerField()),
                ('measurement_date', models.DateTimeField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.department')),
                ('kpi_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.kpi_metric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('employee_department_id', models.AutoField(primary_key=True, serialize=False)),
                ('can_review', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_assign_approver', models.BooleanField(default=False)),
                ('can_assign_executors', models.BooleanField(default=False)),
                ('can_assign_reviewer', models.BooleanField(default=False)),
                ('can_create_tasks', models.BooleanField(default=False)),
                ('can_return_to_work', models.BooleanField(default=False)),
                ('can_return_to_review', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.position'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
