# Generated by Django 4.2.16 on 2024-10-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_task_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creation',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='review',
            new_name='review_time',
        ),
    ]
