# Generated by Django 4.2.16 on 2024-10-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_rename_creation_task_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
