# Generated by Django 4.2.16 on 2024-10-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_user_profile_photo_alter_user_third_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('reviewing', 'Reviewing'), ('assigning', 'Assigning'), ('assigned', 'Assigned'), ('in_work', 'In Work'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
