# Generated by Django 4.2.16 on 2024-10-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedepartment',
            name='can_assign_metrics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('created', 'Создано'), ('reviewing', 'Согласуется'), ('assigning', 'Утверждается'), ('assigned', 'Утверждено'), ('in_work', 'В работе'), ('completed', 'Выполнено')], default='draft', max_length=20),
        ),
    ]
