# Generated by Django 4.2.16 on 2024-10-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_employeedepartment_can_assign_metrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedepartment',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
