# Generated by Django 4.2.16 on 2024-10-29 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_employeekpi_multiplier_taskkpi_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_tasks_count', models.IntegerField(default=0)),
                ('total_time_hours', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
