# Generated by Django 4.2.16 on 2024-10-29 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_usertaskmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertaskmetric',
            name='average_task_completion_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertaskmetric',
            name='completed_task_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertaskmetric',
            name='high_priority_tasks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertaskmetric',
            name='max_task_completion_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertaskmetric',
            name='min_task_completion_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertaskmetric',
            name='on_time_completion_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertaskmetric',
            name='task_efficiency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertaskmetric',
            name='task_revisions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertaskmetric',
            name='completed_tasks_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usertaskmetric',
            name='total_time_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usertaskmetric',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
